"""remove custody_events and integrity_checks

Revision ID: 02677bad017f
Revises: fa1497c19db3
Create Date: 2026-06-29 17:28:14.693832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02677bad017f'
down_revision: Union[str, None] = 'fa1497c19db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custody_events_evidence_id'), table_name='custody_events')
    op.drop_index(op.f('ix_custody_events_from_user_id'), table_name='custody_events')
    op.drop_index(op.f('ix_custody_events_occurred_at'), table_name='custody_events')
    op.drop_index(op.f('ix_custody_events_to_user_id'), table_name='custody_events')
    op.drop_table('custody_events')
    op.drop_index(op.f('ix_integrity_checks_checked_at'), table_name='integrity_checks')
    op.drop_index(op.f('ix_integrity_checks_checked_by'), table_name='integrity_checks')
    op.drop_index(op.f('ix_integrity_checks_evidence_file_id'), table_name='integrity_checks')
    op.drop_index(op.f('ix_integrity_checks_is_match'), table_name='integrity_checks')
    op.drop_table('integrity_checks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrity_checks',
    sa.Column('check_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('evidence_file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('checked_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('expected_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('computed_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('is_match', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['checked_by'], ['users.user_id'], name=op.f('integrity_checks_checked_by_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_file_id'], ['evidence_files.file_id'], name=op.f('integrity_checks_evidence_file_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('check_id', name=op.f('integrity_checks_pkey'))
    )
    op.create_index(op.f('ix_integrity_checks_is_match'), 'integrity_checks', ['is_match'], unique=False)
    op.create_index(op.f('ix_integrity_checks_evidence_file_id'), 'integrity_checks', ['evidence_file_id'], unique=False)
    op.create_index(op.f('ix_integrity_checks_checked_by'), 'integrity_checks', ['checked_by'], unique=False)
    op.create_index(op.f('ix_integrity_checks_checked_at'), 'integrity_checks', ['checked_at'], unique=False)
    op.create_table('custody_events',
    sa.Column('custody_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('evidence_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('COLLECTED', 'TRANSFERRED', 'CHECKED_OUT', 'CHECKED_IN', 'RELEASED', 'DISPOSED', name='custodyaction'), autoincrement=False, nullable=False),
    sa.Column('from_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('to_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signature_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.evidence_id'], name=op.f('custody_events_evidence_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.user_id'], name=op.f('custody_events_from_user_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.user_id'], name=op.f('custody_events_to_user_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('custody_id', name=op.f('custody_events_pkey'))
    )
    op.create_index(op.f('ix_custody_events_to_user_id'), 'custody_events', ['to_user_id'], unique=False)
    op.create_index(op.f('ix_custody_events_occurred_at'), 'custody_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_custody_events_from_user_id'), 'custody_events', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_custody_events_evidence_id'), 'custody_events', ['evidence_id'], unique=False)
    # ### end Alembic commands ###
