"""add users supervisor_id

Revision ID: 14f1bea4590d
Revises: 49fbe6f441d7
Create Date: 2026-07-21 02:22:49.817132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f1bea4590d'
down_revision: Union[str, None] = '49fbe6f441d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supervisor_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_supervisor_id'), 'users', ['supervisor_id'], unique=False)
    # ตั้งชื่อ constraint เอง — autogenerate ใส่ None มาให้ ซึ่งทำให้ downgrade() ลบไม่ได้
    op.create_foreign_key(
        'fk_users_supervisor_id_users', 'users', 'users',
        ['supervisor_id'], ['user_id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_supervisor_id_users', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_supervisor_id'), table_name='users')
    op.drop_column('users', 'supervisor_id')
    # ### end Alembic commands ###
