"""add query audit action

Revision ID: 4eac92bd79a8
Revises: 14f1bea4590d
Create Date: 2026-08-17 22:00:57.922683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eac92bd79a8'
down_revision: Union[str, None] = '14f1bea4590d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'QUERY'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
