"""initial schema

Revision ID: 5ffef7ebb547
Revises: 
Create Date: 2026-07-02 02:17:51.673711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ffef7ebb547'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('badge_number', sa.String(length=20), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='officer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_trails',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('VIEW', 'DOWNLOAD', name='auditaction'), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILED', name='auditresult'), server_default='SUCCESS', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('accessed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_trails_accessed_at'), 'audit_trails', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_audit_trails_created_at'), 'audit_trails', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_trails_entity_id'), 'audit_trails', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_trails_entity_type'), 'audit_trails', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_trails_user_id'), 'audit_trails', ['user_id'], unique=False)
    op.create_table('cases',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'CLOSED', 'ARCHIVED', name='casestatus'), server_default='OPEN', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assigned_officer', sa.UUID(), nullable=True),
    sa.Column('incident_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_assigned_officer'), 'cases', ['assigned_officer'], unique=False)
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_created_by'), 'cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('evidence_items',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('evidence_number', sa.String(length=30), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'FLAGGED', 'REJECTED', 'ARCHIVED', name='evidencestatus'), server_default='PENDING', nullable=False),
    sa.Column('is_watermarked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_blockchain_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('captured_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_items_case_id'), 'evidence_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_evidence_number'), 'evidence_items', ['evidence_number'], unique=True)
    op.create_index(op.f('ix_evidence_items_status'), 'evidence_items', ['status'], unique=False)
    op.create_index(op.f('ix_evidence_items_uploaded_by'), 'evidence_items', ['uploaded_by'], unique=False)
    op.create_table('blockchain_transactions',
    sa.Column('tx_internal_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('REGISTER', 'VERIFY', 'UPLOAD', 'ACCESS', 'TRANSFER', 'FLAG', name='blockchainaction'), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('contract_address', sa.String(length=42), nullable=True),
    sa.Column('input_data_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('gas_used', sa.Integer(), nullable=True),
    sa.Column('block_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.evidence_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tx_internal_id')
    )
    op.create_index(op.f('ix_blockchain_transactions_evidence_id'), 'blockchain_transactions', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_blockchain_transactions_initiated_by'), 'blockchain_transactions', ['initiated_by'], unique=False)
    op.create_index(op.f('ix_blockchain_transactions_status'), 'blockchain_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_blockchain_transactions_tx_hash'), 'blockchain_transactions', ['tx_hash'], unique=False)
    op.create_table('evidence_files',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', name='filetype'), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.evidence_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_evidence_files_evidence_id'), 'evidence_files', ['evidence_id'], unique=False)
    op.create_table('access_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('VIEW', 'DOWNLOAD', name='auditaction'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('tx_internal_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILED', name='auditresult'), server_default='SUCCESS', nullable=False),
    sa.Column('accessed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.evidence_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tx_internal_id'], ['blockchain_transactions.tx_internal_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_access_logs_accessed_at'), 'access_logs', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_access_logs_evidence_id'), 'access_logs', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_access_logs_user_id'), 'access_logs', ['user_id'], unique=False)
    op.create_table('watermark_records',
    sa.Column('watermark_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('embedded_by', sa.UUID(), nullable=True),
    sa.Column('original_image_id', sa.UUID(), nullable=True),
    sa.Column('watermarked_image_id', sa.UUID(), nullable=True),
    sa.Column('watermark_hash', sa.String(length=64), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('embed_band', sa.String(length=50), nullable=True),
    sa.Column('embedded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dwt_level', sa.Integer(), nullable=True),
    sa.Column('embed_params', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['embedded_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.evidence_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['original_image_id'], ['evidence_files.file_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['watermarked_image_id'], ['evidence_files.file_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('watermark_id')
    )
    op.create_index(op.f('ix_watermark_records_evidence_id'), 'watermark_records', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watermark_records_evidence_id'), table_name='watermark_records')
    op.drop_table('watermark_records')
    op.drop_index(op.f('ix_access_logs_user_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_evidence_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_accessed_at'), table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_index(op.f('ix_evidence_files_evidence_id'), table_name='evidence_files')
    op.drop_table('evidence_files')
    op.drop_index(op.f('ix_blockchain_transactions_tx_hash'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_status'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_initiated_by'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_evidence_id'), table_name='blockchain_transactions')
    op.drop_table('blockchain_transactions')
    op.drop_index(op.f('ix_evidence_items_uploaded_by'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_status'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_evidence_number'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_case_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_by'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_officer'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_trails_user_id'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_entity_type'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_entity_id'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_created_at'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_accessed_at'), table_name='audit_trails')
    op.drop_table('audit_trails')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
